""" 
these models are indepndent of the incoming json schema. The candidate adapter is responsible for converting raw JSON into these domain models.
"""
from dataclasses import dataclass,field
from typing import List,Optional

@dataclass(slots=True)
class PersonalInfo:
    """Basic personal details."""

    name: str
    email: str
    phone: str
    cnic: str
    location: str
@dataclass(slots=True)
class Education:
    """Educational qualification."""

    degree_raw: str
    degree_level: str
    field: str
    institution: str
    graduation_year: int
    is_current: bool
    cgpa: Optional[float] = None
@dataclass(slots=True)
class Experience:
    """Professional work experience."""

    title: str
    organization: str
    start_date: str
    end_date: Optional[str]
    is_current: bool
    duration_months: int
@dataclass(slots=True)
class Certification:
    """Professional certification."""

    name: str
    year: int
@dataclass(slots=True)
class URLs:
    """Professional profile links."""

    github: str = ""
    linkedin: str = ""
    portfolio: List[str] = field(default_factory=list)
@dataclass(slots=True)
class Flags:
    """Data quality flags generated by previous modules."""

    missing_fields: List[str] = field(default_factory=list)
    low_confidence_fields: List[str] = field(default_factory=list)
    ner_review_needed: bool = False
@dataclass(slots=True)
class Candidate:
    """
    Standardized Candidate object used by Module 4.

    This class should never depend on raw JSON.
    """

    id: str

    personal_info: PersonalInfo

    education: List[Education]

    experience: List[Experience]

    total_experience_years: float

    skills: List[str]

    certifications: List[Certification]

    urls: URLs

    flags: Flags

    resume_text: str